export type { Rng } from './random.ts';
export { rng } from './random.ts';
export type { VirtualClock } from './clock.ts';
export { virtualClock } from './clock.ts';
export type { ServerCounters, StoredDocument } from './fake-paperless.ts';
export { FakePaperless } from './fake-paperless.ts';
export type { AttemptFault, FaultProfile } from './faults.ts';
export { CALM, FLAKY, HOSTILE, rollAttempt, rollKill, rollOffline } from './faults.ts';
export type { SimOptions, SimResult } from './sim.ts';
export { runSim, seeds } from './sim.ts';
